Reduce cursor opens when fetching committed atoms
radixdlt/radixdlt-core pull request #126
Opened 2020-07-01 16:07 UTC by lfeagan

The current implementation in CommittedAtomsStore.getCommittedAtoms uses an approach that first pulls all committed atom ids and then fetches them by repeatedly fetching individual LedgerEntry. This results in repeatedly opening a new cursor. It is more efficient to address this by scrolling a single cursor. Architecturally, this could be done in one of two ways:

1. adding a new method to the ledger store that takes a Collection of AtomIDs and returns a List of LedgerEntry
2. adding a new method to the ledger store that returns an ImmutableList of committed LedgerEntry, rather than AtomID
3. 

As the LedgerEntryStoreView already has a precedent of returning LedgerEntry (no new imports), I feel it makes the most sense to add the new method getNextCommittedLedgerEntries, in the spirit of the existing method getNextCommitted, but returning LedgerEntry rather than AtomID. (Is it just me or is anyone else blah on AID plural being AIDs?)

This PR includes these changes, as well as a new integration test and fixes to unit tests.

2020-07-03 07:26 UTC, talekhinezh requested changes
Looks good overall, just a few cleanups before we can merge this

2020-07-03 07:26 UTC, talekhinezh commented on radixdlt/src/main/java/com/radixdlt/store/berkeley/BerkeleyLedgerEntryStore.java
> +			 Cursor uqCursor = this.uniqueIndices.openCursor(null, null)) {
Extra white space

2020-07-03 07:26 UTC, talekhinezh commented on radixdlt/src/main/java/com/radixdlt/store/LedgerEntryStoreView.java
>  	ImmutableList<AID> getNextCommitted(long stateVersion, int limit);
Since `getNextCommitted` is no longer being used, please remove

2020-07-06 22:06 UTC, lfeagan commented
Hi,
Removed getNextCommitted and related code and removed white space. Should be good now unless I missed some whitespace. Checkstyle was happy.

2020-07-07 09:55 UTC, talekhinezh approved these changes

2020-07-08 10:25 UTC, clstrfsck approved these changes
LGTM

2020-07-08 10:28 UTC, merged