Integration/rm events+fix vertex store
radixdlt/radixdlt-core pull request #221
Opened 2020-09-30 04:57 UTC by talekhinezh

2020-09-30 15:47 UTC, siy approved these changes
LGTM

2020-09-30 15:47 UTC, siy commented on radixdlt/src/integration/java/com/radixdlt/integration/distributed/simulation/network/OneNodePerEpochResponseDropper.java
> +		BFTNode node = nodeToDrop.putIfAbsent(getEpochResponse.getEpochProof().getEpoch(), messageInTransit.getSender());
Since only one value is stored, it might be simpler to use AtomicReference. Since Java 9 it has new method compareAndExchange() which will be useful in this use case.

2020-09-30 16:28 UTC, clstrfsck requested changes
There is a suspicious commented out test that needs addressing somehow.  Not obvious if the fix is additional comments explaining why the test is commented out, uncommenting the test or removing it altogether.

Some Javadoc has been broken by API changes and needs fixing.

Can we also please remove "_count" from the end of the fork counter for consistency with the other counter names?

Some other minor nits that you can deal with as you see fit.

2020-09-30 16:28 UTC, clstrfsck commented on radixdlt/src/main/java/com/radixdlt/consensus/bft/SignedNewViewToLeaderSender.java
> +public final class SignedNewViewToLeaderSender implements ProceedToViewSender {
Ah, crap.  This is going to change the "removing new view" stuff I'm working on a bit.

2020-09-30 16:28 UTC, clstrfsck commented on radixdlt/src/main/java/com/radixdlt/consensus/epoch/EpochManager.java
> +			log.info("{}: EPOCH_CHANGE: broadcasting next epoch", this.self);
Would be good to start removing `this.self` from logs when they get touched.  Looks like this was just a logger -> log rename tho.

2020-09-30 16:28 UTC, clstrfsck commented on radixdlt/src/main/java/com/radixdlt/consensus/epoch/EpochManager.java
> +				log.info("{}: Ignoring old epoch {} current {}", this.self, response, this.currentEpoch);
Remove this.self from log.

2020-09-30 16:28 UTC, clstrfsck commented on radixdlt/src/main/java/com/radixdlt/consensus/liveness/ExponentialTimeoutPacemaker.java
> +			log.trace("LOCAL_TIMEOUT: Ignoring {}", () -> view);
Don't need the lambda here.  Should just be `log.trace("LOCAL_TIMEOUT: Ignoring {}", view)`.

2020-09-30 16:28 UTC, clstrfsck commented on radixdlt/src/main/java/com/radixdlt/consensus/liveness/Pacemaker.java
>  	 * @return optional with view, if the pacemaker changes views within the call
Javadoc broken now.

2020-09-30 16:28 UTC, clstrfsck commented on radixdlt/src/main/java/com/radixdlt/consensus/liveness/Pacemaker.java
>  	 * @return optional with view, if the pacemaker changes views within the call
Javadoc broken.

2020-09-30 16:28 UTC, clstrfsck commented on radixdlt/src/main/java/com/radixdlt/counters/SystemCounters.java
> +		BFT_VERTEX_STORE_FORK_COUNT("bft.vertex_store_fork_count"),
Maybe `bft.vertex_store_total_forks`?  It sounds a bit like this is an instantaneous count of the forks in the store currently.

2020-09-30 16:28 UTC, clstrfsck commented on radixdlt/src/main/java/com/radixdlt/counters/SystemCounters.java
> +		BFT_VERTEX_STORE_FORK_COUNT("bft.vertex_store_fork_count"),
Or even just `bft.vertex_store_forks`.

2020-09-30 16:28 UTC, clstrfsck commented on radixdlt/src/test/java/com/radixdlt/consensus/bft/VertexStoreTest.java
> +	/*
Oops.  What happened here?  Should this be ignored or removed?

2020-09-30 16:43 UTC, talekhinezh commented on radixdlt/src/main/java/com/radixdlt/consensus/bft/SignedNewViewToLeaderSender.java
> +public final class SignedNewViewToLeaderSender implements ProceedToViewSender {
Yes, this should actually make it easier to implement since sending new-view messages isn't a necessary part of BFTReducer.

2020-09-30 17:11 UTC, talekhinezh commented on radixdlt/src/integration/java/com/radixdlt/integration/distributed/simulation/network/OneNodePerEpochResponseDropper.java
> +		BFTNode node = nodeToDrop.putIfAbsent(getEpochResponse.getEpochProof().getEpoch(), messageInTransit.getSender());
How would the implementation look like? As we still require a map?

2020-10-01 07:58 UTC, clstrfsck approved these changes

2020-10-01 09:42 UTC, merged