Feature/bft sync retries
radixdlt/radixdlt-core pull request #235
Opened 2020-10-19 04:01 UTC by talekhinezh

2020-10-19 18:39 UTC, clstrfsck requested changes
Some comments about documentation and other minor bits that need some attention.

Also, this PR seems to be an amalgamation of two unrelated pieces of work, one dealing with sync timings, and the other an overhaul of the network simulation.  Maybe it wasn't possible to complete the sync work without doing the other work, but it doesn't look like it to me.

Finally, not really sure about the merits of using RunWith(Parameterized.class) with small numbers of test cases.

2020-10-19 18:39 UTC, clstrfsck commented on radixdlt/src/main/java/com/radixdlt/consensus/sync/LocalGetVerticesRequest.java
> +	public boolean equals(Object o)  {
Should have an EqualsVerifier test for this.

Also should have a toString as well.

2020-10-19 18:39 UTC, clstrfsck commented on radixdlt/src/main/java/com/radixdlt/consensus/sync/BFTSyncPatienceMillis.java
> +public @interface BFTSyncPatienceMillis {
Can we use the existing Named annotation for this?

If not, please add some Javadoc, for the class.

2020-10-19 18:39 UTC, clstrfsck commented on radixdlt/src/main/java/com/radixdlt/consensus/sync/BFTSyncPatienceMillis.java
> +@Target({ FIELD, PARAMETER, METHOD })
Not sure METHOD is valid here?

2020-10-19 18:39 UTC, clstrfsck commented on radixdlt/src/main/java/com/radixdlt/consensus/sync/BFTSyncRequestTimeoutProcessor.java
> +public interface BFTSyncRequestTimeoutProcessor {
Javadoc.

2020-10-19 18:39 UTC, clstrfsck commented on radixdlt/src/main/java/com/radixdlt/consensus/sync/LocalGetVerticesRequest.java
> +public final class LocalGetVerticesRequest {
Javadoc.

2020-10-19 18:39 UTC, clstrfsck commented on radixdlt/src/integration/java/com/radixdlt/integration/distributed/deterministic/network/ControlledSender.java
> +import com.radixdlt.utils.Pair;
Is this used?

2020-10-19 18:39 UTC, clstrfsck commented on radixdlt/src/integration/java/com/radixdlt/integration/distributed/deterministic/network/ControlledSender.java
> +		// Ignore bft sync timeouts
A log here would surely help at some point in the future.

2020-10-19 18:39 UTC, clstrfsck commented on radixdlt/src/integration/java/com/radixdlt/integration/distributed/simulation/network/MessageDropper.java
> +		this.msgClassesToDrop = Arrays.stream(msgClasses).collect(Collectors.toSet());
Better as `ImmutableSet.copyOf(msgClasses)`

2020-10-19 18:39 UTC, clstrfsck commented on radixdlt/src/integration/java/com/radixdlt/integration/distributed/simulation/network/MessageDropper.java
> +		this.msgClassesToDrop = Arrays.stream(msgClasses).collect(Collectors.toSet());
Body should just be `this(null, 0.0, msgClasses)`

2020-10-19 18:39 UTC, clstrfsck commented on radixdlt/src/integration/java/com/radixdlt/integration/distributed/simulation/network/SimulationNetwork.java
>  		this.receivedMessages = ReplaySubject.<MessageInTransit>create(20) // To catch startup timing issues
I think this should be `createWithSize(20)` — not sure we want to keep all of the messages.

2020-10-19 18:39 UTC, clstrfsck commented on radixdlt/src/integration/java/com/radixdlt/integration/distributed/simulation/network/SimulationNetwork.java
> +					/*
This commented out code needs some explanation of why it is commented out, and what needs to be done to bring it back.

2020-10-19 18:39 UTC, clstrfsck commented on radixdlt/src/integration/java/com/radixdlt/integration/distributed/simulation/tests/consensus/OutOfOrderTest.java
> +		System.out.println(statistics);
Should be logged rather than printed.

2020-10-19 18:39 UTC, clstrfsck commented on radixdlt/src/integration/java/com/radixdlt/integration/distributed/simulation/tests/consensus_ledger_sync/ByzantineSyncTest.java
> +	public static Collection<Object[]> numNodes() {
What is the thinking behind this?  Doesn't seem like a good tradeoff between complexity and utility.

2020-10-19 19:25 UTC, talekhinezh commented on radixdlt/src/main/java/com/radixdlt/consensus/sync/BFTSyncPatienceMillis.java
> +@Target({ FIELD, PARAMETER, METHOD })
Could be if used with @Provides

2020-10-20 08:02 UTC, clstrfsck commented on radixdlt/src/main/java/com/radixdlt/consensus/sync/BFTSyncPatienceMillis.java
> +@Target({ FIELD, PARAMETER, METHOD })
Yeah, OK fair enough.

2020-10-20 08:05 UTC, clstrfsck commented on radixdlt/src/integration/java/com/radixdlt/integration/distributed/simulation/tests/consensus/FProposalsPerViewDropperTest.java
> +import static org.assertj.core.api.AssertionsForInterfaceTypes.assertThat;
Should be `org.assertj.core.api.Assertions.assertThat`

2020-10-20 08:06 UTC, clstrfsck commented on radixdlt/src/integration/java/com/radixdlt/integration/distributed/simulation/tests/consensus/FProposalsPerViewDropperTest.java
> +		assertThat(results.getCheckResults()).allSatisfy((name, error) -> AssertionsForClassTypes.assertThat(error).isNotPresent());
Shouldn't have (different) class for statically imported method.

2020-10-20 08:06 UTC, clstrfsck commented on radixdlt/src/integration/java/com/radixdlt/integration/distributed/simulation/tests/consensus/OutOfOrderTest.java
> +import static org.assertj.core.api.AssertionsForInterfaceTypes.assertThat;
Should be `org.assertj.core.api.Assertions.assertThat`

2020-10-20 08:07 UTC, clstrfsck commented on radixdlt/src/integration/java/com/radixdlt/integration/distributed/simulation/tests/consensus/OutOfOrderTest.java
> +		assertThat(results.getCheckResults()).allSatisfy((name, error) -> AssertionsForClassTypes.assertThat(error).isNotPresent());
Shouldn't have different class qualification for statically imported method.

2020-10-20 10:13 UTC, siy requested changes

2020-10-20 10:13 UTC, siy commented on radixdlt/build.gradle
> +    compile 'com.radixdlt:radix-engine-library:feature~epoch-high-view-SNAPSHOT'
Perhaps it worth to merge radix-engine-library changes first and omit change in dependencies.

2020-10-20 10:13 UTC, siy commented on radixdlt/src/integration/java/com/radixdlt/integration/distributed/simulation/network/FProposalsPerViewDropper.java
> +				List<BFTNode> nodes = new LinkedList<>(validatorSet);
Since code below uses random access to list elements, ArrayList might be a better fit here.

2020-10-20 10:13 UTC, siy commented on radixdlt/src/integration/java/com/radixdlt/integration/distributed/simulation/network/InOrderChannels.java
> +			if (msg.getSender().equals(receiver)) {
Moving this code to dedicated method would make whole processing pipeline more readable.

2020-10-20 10:13 UTC, siy commented on radixdlt/src/integration/java/com/radixdlt/integration/distributed/simulation/network/InOrderChannels.java
> +				int delayCarryover = (int) Math.max(msg1.time() + msg1.value().getDelay() - msg2.time(), 0);
Same as above: moving this code to dedicated method would make whole processing pipeline more readable.

2020-10-21 05:04 UTC, merged