[RPNV1-799] Dockerfile.test for test container
radixdlt/radixdlt-core pull request #269
Opened 2020-11-18 12:46 UTC by shambupujar

2020-11-20 08:19 UTC, siy approved these changes
LGTM

2020-11-20 09:01 UTC, clstrfsck requested changes

2020-11-20 09:01 UTC, clstrfsck commented on docker/Dockerfile.test
> +FROM ubuntu:16.04
We need to stop using Ubuntu 16.04.  LTS support for this runs out in April next year, and that is not a time that we want to be scrambling to change things.

2020-11-20 09:01 UTC, clstrfsck commented on gradle.properties
> +org.gradle.jvmargs=-Xmx4g -XX:MaxPermSize=2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
4Gb seems completely over the top for a build system.  Do we know what this number really should be?

2020-11-20 09:01 UTC, clstrfsck commented on gradlew
> +DEFAULT_JVM_OPTS='"-Xmx2048m" "-Xms1024m"'
Another 2GiB of RAM here means that we are using 6GiB of ram for the build system, if we account for a single daemon.

This seems completely ridiculous.  This is many, many times more RAM than the entire source code + build products (total of ~170MiB).

2020-11-23 09:29 UTC, clstrfsck approved these changes
Looks OK, but maybe installing the JDK headless package will reduce disk usage from unnecessary libraries for us?

2020-11-23 09:29 UTC, clstrfsck commented on docker/Dockerfile.test
> +    apt install -yq openjdk-11-jdk
Is there a headless package we could install?  Perhaps this would reduce the number of XWindows packages we need to pull in.

2020-12-02 11:52 UTC, merged